### ISSUE TITLE
Api key zichtbaar

### ISSUE THREAD

**Issue by DanielvandeVelde** [Senpaizuri/web-app-from-scratch-18-19#2]
https://github.com/Senpaizuri/web-app-from-scratch-18-19/blob/e715ea441370bf19f88e4b67657d061217237536/week1/public/js/app.js#L19

Op dit moment is je api-key zichtbaar.
Je kan dit het beste even wijzigen aangezien dit gevoelige informatie is.
Hoe je dan kan doen is onder andere [hier](https://gist.github.com/derzorngottes/3b57edc1f996dddcab25) te vinden.

**Comment by Senpaizuri** [comment]
Thanks for the tip, I just revised my code to adjust for the key
