### ISSUE TITLE
Be consistent

### ISSUE THREAD

**Issue by maanlamp** [Senpaizuri/web-app-from-scratch-18-19#4]
https://github.com/Senpaizuri/web-app-from-scratch-18-19/blob/6c14328cfc0e5a79ef766f4c336f78a310e45d22/week1/public/js/app.js#L13

You're using semicolons, but only selectively. Either use them or not, but don't just throw them in whenever you feel like it :p

https://github.com/Senpaizuri/web-app-from-scratch-18-19/blob/6c14328cfc0e5a79ef766f4c336f78a310e45d22/week1/public/js/app.js#L41

You're using `function` and arrow functions `=>`. You seem to not need to use any over the other, so it's best you make a choice. Arrow or normal functions? The choice is yours!

**Comment by Senpaizuri** [comment]
Thanks, I just revised the code
